name: CI Lua 5.2

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ReportOnLua:
    name: Lua Performance Test Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.2.4"

      - name: Show Lua Version Report
        working-directory: ${{ github.workflow.workflow_root }}
        run: |
          lua -v

      - name: Run Lua Performance Test
        working-directory: ${{ github.workflow.workflow_root }}
        run: |
          lua main.lua run
